run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - nilerr
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  govet:
    enable-all: true
    disable:
      - fieldalignment
  goimports:
    local-prefixes: github.com/xokvictor/whoop-mcp
  misspell:
    locale: US

issues:
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - errcheck
    # Exclude bodyclose for test files (httptest.Server handles this)
    - path: _test\.go
      linters:
        - bodyclose
